int fibo(int,int*);
int concat(int *array1, int len_of_array1, int *array2, int len_of_array2, int *result_array);
int filter(int *array, int length, int threshold, int **result_array);
int reverse_2(int *array, int length, int *result_array);
int slice(int *array,int len_of_array,int start_index, int end_index, int **result_array);
int prime(int start_range,int end_range,int **result_array);
int check_prime(int);
int stringlen(char *);
int stringcomp(char *, char *);
int forEach(int *,int ,void (*)(int,int,int *));
int forEach_float(float *,int ,void (*)(float,int,float *));
int forEach_string(char **,int ,void (*)(char *,int,char **));
int filter_int(int *, int, int (*)(int,int,int *),int **);
int filter_float(float *, int, int (*)(float,int,float *),float **);
int filter_char(char *,int ,int (*)(char,int,char *),char **);
int filter_string(char **,int ,int (*)(char *,int,char **),char ***);
int * map_int(int *,int,int (*)(int,int,int*));
float * map_float(float *,int,float (*)(float,int,float*));
char * map_char(char *,int,char (*)(char,int,char *));
char ** map_string(char **,int,char *(*)(char*,int,char **));
int reduce_int(int *,int ,int (*)(int ,int ,int ,int *),int );
float reduce_float(float *,int ,float (*)(float ,float ,int ,float *),float);
char reduce_char(char *,int ,char (*)(char ,char ,int ,char *),char);